Repository rm-hull/luma.core, pull requests merged in 2020-10, with the labels that each got.

#198 tests: use pathlib
  tests/helpers.py
  tests/test_bitmap_font.py
  tests/test_character.py
Labels: tests

#199 tests: fix failure
  tests/helpers.py
  tests/reference/images/hotspot.png
  tests/reference/images/portrait.png
  tests/reference/images/set_position.png
Labels: tests

#210 tests: fix pytest 6.x coverage
  .coveragerc
  setup.py
  tox.ini
Labels: tests

#205 Improved diff-to-previous framebuffer performance
  CHANGES.rst
  luma/core/__init__.py
  luma/core/cmdline.py
  luma/core/framebuffer.py
  tests/test_cmdline.py
  tests/test_framebuffer.py
  tox.ini
Labels: enhancement

#208 travis: test on ubuntu focal
  .travis.yml
Labels: build
